# Generated by Django 6.0.3 on 2026-04-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('consent', 'Informed Consent Form'), ('biodata', 'Client Biodata Form'), ('contract', 'Service Contract')], help_text='Type of document', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Document title shown on website', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of what the document contains')),
                ('file', models.FileField(help_text='Upload PDF file', upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Downloadable Document',
                'verbose_name_plural': 'Downloadable Documents',
                'ordering': ['document_type'],
            },
        ),
    ]
