# Generated by Django 6.0.3 on 2026-04-16 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_seed_roles_and_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrecord',
            name='session_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
